package vista;

import java.util.HashSet;
import logica.DirectorioTelefonico;

public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public static DirectorioTelefonico directorio = new DirectorioTelefonico();
    public static HashSet listaCiudades = new HashSet<>();

    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMenuPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmContactos = new javax.swing.JMenu();
        jmiAgregarContacto = new javax.swing.JMenuItem();
        jmiBuscarContacto = new javax.swing.JMenuItem();
        jmiBorrarContacto = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmiDirectorio = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        jmiAgregarCiudad = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpMenuPrincipalLayout = new javax.swing.GroupLayout(jdpMenuPrincipal);
        jdpMenuPrincipal.setLayout(jdpMenuPrincipalLayout);
        jdpMenuPrincipalLayout.setHorizontalGroup(
            jdpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jdpMenuPrincipalLayout.setVerticalGroup(
            jdpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jmContactos.setText("Contactos");
        jmContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmContactosActionPerformed(evt);
            }
        });

        jmiAgregarContacto.setText("Agregar contacto");
        jmiAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarContactoActionPerformed(evt);
            }
        });
        jmContactos.add(jmiAgregarContacto);

        jmiBuscarContacto.setText("Buscar contacto");
        jmiBuscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarContactoActionPerformed(evt);
            }
        });
        jmContactos.add(jmiBuscarContacto);

        jmiBorrarContacto.setText("Borrar contacto");
        jmiBorrarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarContactoActionPerformed(evt);
            }
        });
        jmContactos.add(jmiBorrarContacto);

        jMenuBar1.add(jmContactos);

        jmDirectorio.setText("Directorio");
        jmDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDirectorioActionPerformed(evt);
            }
        });

        jmiDirectorio.setText("Directorio");
        jmiDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDirectorioActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiDirectorio);

        jMenuBar1.add(jmDirectorio);

        jmCiudades.setText("Ciudades");
        jmCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCiudadesActionPerformed(evt);
            }
        });

        jmiAgregarCiudad.setText("Agregar ciudad");
        jmiAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarCiudadActionPerformed(evt);
            }
        });
        jmCiudades.add(jmiAgregarCiudad);

        jMenuBar1.add(jmCiudades);

        jmSalir.setText("Salir");

        jmiSalir.setText("Salir");
        jmSalir.add(jmiSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMenuPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiBuscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarContactoActionPerformed
        frmBuscar buscarContacto = new frmBuscar(); //instancia del jinternalframe
        jdpMenuPrincipal.add(buscarContacto); //agregar la instancia del jif al jdesktoppane
        buscarContacto.setVisible(true); //hacerlo visible
    }//GEN-LAST:event_jmiBuscarContactoActionPerformed

    private void jmiAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarContactoActionPerformed
        frmAgregar agregarContacto = new frmAgregar(); //instancia del jinternalframe
        jdpMenuPrincipal.add(agregarContacto); //agregar la instancia del jif al jdesktoppane
        agregarContacto.setVisible(true); //hacerlo visible
    }//GEN-LAST:event_jmiAgregarContactoActionPerformed

    private void jmContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmContactosActionPerformed

    private void jmiBorrarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarContactoActionPerformed
        frmBorrar borrarContacto = new frmBorrar(); //instancia del jinternalframe
        jdpMenuPrincipal.add(borrarContacto); //agregar la instancia del jif al jdesktoppane
        borrarContacto.setVisible(true); //hacerlo visible
    }//GEN-LAST:event_jmiBorrarContactoActionPerformed

    private void jmDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmDirectorioActionPerformed

    private void jmiDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDirectorioActionPerformed

    }//GEN-LAST:event_jmiDirectorioActionPerformed

    private void jmiAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarCiudadActionPerformed
        frmAgregarCiudad agregarCiudad = new frmAgregarCiudad(); //instancia del jinternalframe
        jdpMenuPrincipal.add(agregarCiudad); //agregar la instancia del jif al jdesktoppane
        agregarCiudad.setVisible(true); //hacerlo visible
    }//GEN-LAST:event_jmiAgregarCiudadActionPerformed

    private void jmCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCiudadesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpMenuPrincipal;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmContactos;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAgregarCiudad;
    private javax.swing.JMenuItem jmiAgregarContacto;
    private javax.swing.JMenuItem jmiBorrarContacto;
    private javax.swing.JMenuItem jmiBuscarContacto;
    private javax.swing.JMenuItem jmiDirectorio;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
